#!/bin/bash
# GeosChem Classic Runner Script

set -e

SIMULATION=""
RESOLUTION=""
CONFIG_DIR="/workspace/config"
DATA_DIR="/workspace/data"
OUTPUT_DIR="/workspace/output"
START_DATE=""
END_DATE=""
DRY_RUN=""

# Parse arguments (passed from entrypoint)
while [[ $# -gt 0 ]]; do
    case $1 in
        --simulation) SIMULATION="$2"; shift 2;;
        --resolution) RESOLUTION="$2"; shift 2;;
        --config-dir) CONFIG_DIR="$2"; shift 2;;
        --data-dir) DATA_DIR="$2"; shift 2;;
        --output-dir) OUTPUT_DIR="$2"; shift 2;;
        --start-date) START_DATE="$2"; shift 2;;
        --end-date) END_DATE="$2"; shift 2;;
        --dry-run) DRY_RUN=1; shift;;
        *) echo "Unknown argument: $1"; exit 1;;
    esac
done

echo "Running GeosChem Classic Mode"
echo "Simulation: $SIMULATION"
echo "Resolution: $RESOLUTION"

# Set up run directory
RUN_DIR="$OUTPUT_DIR/classic_${SIMULATION}_${RESOLUTION}_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$RUN_DIR"

# Copy configuration template
TEMPLATE_DIR="/opt/geoschem/run_templates/${SIMULATION}"
if [[ -d "$TEMPLATE_DIR" ]]; then
    echo "Copying configuration from $TEMPLATE_DIR"
    cp -r "$TEMPLATE_DIR"/* "$RUN_DIR/"
else
    echo "Warning: No template found for $SIMULATION, creating basic setup"
    # Create basic input.geos and HISTORY.rc
    cat > "$RUN_DIR/input.geos" << EOF
# Basic GeosChem input file
# Simulation: $SIMULATION
# Resolution: $RESOLUTION
# Generated by GeosChem Container
EOF
fi

# Update configuration for this resolution/simulation
cd "$RUN_DIR"

# Set up data directory links
if [[ -d "$DATA_DIR" ]]; then
    echo "Linking input data from $DATA_DIR"
    ln -sf "$DATA_DIR" ExtData
else
    echo "Warning: No input data directory found at $DATA_DIR"
fi

# Configure for number of OpenMP threads
export OMP_NUM_THREADS=$(nproc)
echo "Using $OMP_NUM_THREADS OpenMP threads"

# Validate that we have the GeosChem executable
GEOSCHEM_EXE="/opt/geoschem/classic/bin/geoschem"
if [[ ! -f "$GEOSCHEM_EXE" ]]; then
    echo "Error: GeosChem executable not found at $GEOSCHEM_EXE"
    exit 1
fi

if [[ "$DRY_RUN" ]]; then
    echo "DRY RUN - would execute:"
    echo "cd $RUN_DIR"
    echo "$GEOSCHEM_EXE"
    echo ""
    echo "Configuration files in $RUN_DIR:"
    ls -la "$RUN_DIR"
else
    echo "Starting GeosChem Classic simulation..."
    echo "Working directory: $RUN_DIR"
    echo "Executable: $GEOSCHEM_EXE"
    echo "================================================"
    
    # Execute GeosChem
    exec "$GEOSCHEM_EXE"
fi