aws:
  profile: "aws"  # Required: Use 'aws' profile for consistency
  region: "us-west-2"
  key_pair: "geoschem-builder-key"
  security_group: "sg-geoschem-builder"
  subnet_id: "subnet-xxxxxxxx"
  
batch:
  compute_environment: "geoschem-compute"
  job_queue: "geoschem-queue"
  job_definition: "geoschem-job"